# Site settings

# Basic info

baseurl: ""   
title: "QA × IA – Alberto Barragán"
description: "Destripando QA, automatización E2E y modelos IA"
url: "https://albertobarragan.dev"  
lang: es-ES

future: true

# Build and markdown
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Alberto Barragán


collections:
  posts:
    output: true

---