title:  "QA × IA – Alberto Barragán"
description: "Automatización E2E y modelos de IA."
url: "https://albertobarragan.dev"   
baseurl: ""                         

# ── Habilitar Minimal Mistakes ─────────────────────────────
remote_theme: "mmistakes/minimal-mistakes@4.26.1"  
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache 

# ── Opciones de Minimal Mistakes ───────────────
logo: "/assets/images/logo.png"   
masthead_title: "QA × IA Weekly"  
minimal_mistakes_skin: "air"  

future: true

# Formato de enlaces a posts
permalink: /blog/:year/:month/:day/:slug
paginate: 5                      # cuántos posts por página
paginate_path: "/blog/page:num/" # ruta de las páginas 2,3…